Professional_Networking_Platform/PNP/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import signUp,signUpEntre,signUp1,signUp2, firstPage,profile, messaging, metting, joinMetting, mettingPage, network, logincheck, like,classroom,get_comment,addFriend,signUpStud,search,formProfile,accept_request,reject_request, showCommentForm, addComment,create_cours,ouvrir_pdf, rejoindre_cours,get_posts,add_post,deletePost,ouvrir_pdf,delete_experience,delete_education,delete_skill,delete_language,formEducation,formExperience,roomCreateForm,searchRoom,rejoindre_cours, detail_cours,get_posts,add_post,deletePost,students_page,mes_cours,create_cours,getMessages,messageForm,travaux_et_devoir,creer_devoir,creer_documentation,quitterRoom,members,chat,searchPage,accueil,get_datapoints,update_course_view, delete_course_view,delete_documentation,delete_devoir


app_name = "PNP"

urlpatterns = [
    path("", firstPage , name='firstPage'),

    # registration
    path("", include("django.contrib.auth.urls")),
    path('signUp/', signUp1, name='signUp'),
    path('signUpEntre/', signUpEntre, name='signUpEntre'),
    path('signUpStud/', signUpStud, name='signUpStud'),
    path('signUp1/<int:choix>', signUp, name='signUp1'),
    path('signUp2/', signUp2, name='signUp2'),
    path('logincheck/', logincheck, name='logincheck'),

    # first page after login
    path('firstPage/', firstPage , name='firstPage'),

    # messaging page
    path('messaging/', messaging , name='messaging'),
    path('roomCreateForm/<int:type>/<int:id>/', roomCreateForm , name='roomCreateForm'),
    path('searchRoom/<str:roomname>/', searchRoom , name='searchRoom'),
    path('getMessages/<int:id>/', getMessages , name='getMessages'),
    path('messageForm/<int:id>/', messageForm , name='messageForm'),
    path('quitterRoom/<int:id>/', quitterRoom , name='quitterRoom'),
    path('members/<int:id>/', members , name='members'),
    
    # metting pages
    path('mettingPage/', mettingPage , name='mettingPage'), # metting choix page
    path('metting/', metting , name='metting'), # metting create page
    path('joinMetting/', joinMetting , name='joinMetting'), # metting join page

    # profile page
    path('profile/<str:username>/', profile , name='profile'),
    path('formProfile/<int:id>/<str:username>/', formProfile , name='formProfile'),
    path('delete_experience/<int:id>/<str:username>/', delete_experience , name='delete_experience'),
    path('delete_education/<int:id>/<str:username>/', delete_education , name='delete_education'),
    path('delete_skill/<str:id>/<str:username>/', delete_skill , name='delete_skill'),
    path('delete_language/<str:id>/<str:username>/', delete_language , name='delete_language'),
    path('formEducation/<int:id>/<str:username>/', formEducation , name='formEducation'),
    path('formExperience/<int:id>/<str:username>/', formExperience , name='formExperience'),
    path('chat/<str:username>/', chat , name='chat'),

    # clasroom page
    path('classroom/', classroom , name='classroom'),
    path('classroom/accueil/', accueil, name='accueil'),
     #createcourse
    path('classroom/create/', create_cours, name='create_cours'),
    path('ouvrir_pdf/', ouvrir_pdf, name='ouvrir_pdf'),
    
   
    
    
    # networking
    path('network/', network, name='network'),

    #friends
    path('addFriend/<str:friend>/', addFriend, name='addFriend'),
    path('accept_request/<str:username>', accept_request , name='accept_request'),
    path('reject_request/<str:username>', reject_request , name='reject_request'),

    #chart
    path('get_datapoints.json', get_datapoints, name='get_datapoints'),
    path('firstPage/get_datapoints.json', get_datapoints, name='get_datapoints'),
    
    #post
    path('posts/', get_posts , name='posts'),
    path('addPost/', add_post , name='addPost'),
    path('deletePost/<int:id>/', deletePost , name='deletePost'),
    path('like/<int:postid>/', like , name='like'),
    path('showCommentForm/<int:itemid>/<int:type>/', showCommentForm , name='showCommentForm'),
    path('comment/<int:itemid>/', get_comment , name='comment'),
    path('addComment/<int:itemid>/<int:type>/', addComment , name='addComment'),
    
    #pdf calendrier classroom
    #path('ouvrir-pdf/', ouvrir_pdf, name='ouvrir-pdf'),
    
    path('classroom/rejoindre_cours/', rejoindre_cours, name='rejoindre_cours'),  # Route pour rejoindre un cours
    path('classroom/detail_cours/<str:code>/', detail_cours, name='detail_cours'),
    path('classroom/detail_cours/<str:code>/students/', students_page, name='students_page'),

    path('mes_cours/', mes_cours, name='mes_cours'),

    path('classroom/detail_cours/<str:code>/travaux_et_devoir/', travaux_et_devoir, name='travaux_et_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/devoir/', creer_devoir, name='creer_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/documentation/', creer_documentation, name='creer_documentation'),
        
    path('classroom/detail_cours/<str:code>/update_course/', update_course_view, name='update_course'),
    path('classroom/detail_cours/<str:code_cours>/delete_course/', delete_course_view, name='delete_course'),
    
    path('classroom/detail_cours/<str:code>/delete_doc/<int:documentation_id>/', delete_documentation, name='delete_documentation'),
    path('classroom/detail_cours/<str:code_cours>/travaux_et_devoir/delete_devoir/<int:devoir_id>/', delete_devoir, name='delete_devoir'),
#search
    path('search/<str:username>/<int:type>/', search , name='search'),

    #search Page
    path('searchPage/', searchPage , name='searchPage'),
] + static(settings.STATIC_URL)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
print(settings.MEDIA_ROOT)

Professional_Networking_Platform/Professional_Networking_Platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PNP.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Professional_Networking_Platform/PNP/models/classe.py
from django.db import models
from .teacher import Teacher


#################
# Class model #
class Class(models.Model):
    class_id = models.AutoField(primary_key=True)
    class_name= models.CharField(max_length=100, default='')
    Degree = models.TextField(max_length=100, default='')
    
    #
   # teacher_id = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    #
    #
   # schedule_exams = models.TextField(default='[]')
    #
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.class_name

Professional_Networking_Platform/PNP/models/devoir.py
from django.db import models
from .Cours import Cours

class Devoir(models.Model):
    id = models.AutoField(primary_key=True)  # Ajout de l'identifiant unique
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE )
    titre = models.CharField(max_length=100)
    description = models.TextField()
    fichier_joint = models.FileField(upload_to='creer/devoir/', blank=True, null=True)
    date_limite = models.DateTimeField(blank=True)


    def __str__(self):
        return self.titre

    def get_devoirs_by_code(code_cours):
        return Devoir.objects.filter(cours__code=code_cours)
    
    def delete(self, *args, **kwargs):
        # Ajoutez ici la logique de suppression personnalisée si nécessaire
        super().delete(*args, **kwargs)

Professional_Networking_Platform/PNP/forms/forms.py
from django import forms

from ..models import User, Cv, Cours,Room,Devoir,Documentation
from django.contrib.auth.models import User as auth_user
from django.forms import SelectDateWidget


class MonthYearSelectWidget(SelectDateWidget):
    def __init__(self, *args, **kwargs):
        super(MonthYearSelectWidget, self).__init__(*args, **kwargs)
        self.format = '%Y-%m'  # Set the format to year-month

# signUp2
class SignUpForm(forms.ModelForm):
    introduction = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Introduction'}))
    class Meta:
        model = User
        fields = ['introduction','phone', 'address', 'city', 'country', 'cv', 'photo_profile', 'Visibility']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs['placeholder'] = 'Phone'
        self.fields['address'].widget.attrs['placeholder'] = 'Address'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        self.fields['country'].widget.attrs['placeholder'] = 'Country'


# signUp3
class CVForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company(optional)'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title(optional)'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School(optional)'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree(optional)'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description(optional)'}))
    class Meta:
        model = Cv
        fields = ['skills', 'languages','company', 'job_title', 'description' ,'start_date', 'end_date','school', 'degree', 'start_dateE', 'end_dateE']

        widgets = {
            'introduction': forms.TextInput(attrs={'placeholder': 'Introduction(optional)'}),
            'skills': forms.TextInput(attrs={'placeholder': 'Skills(separeted by , ex: HTML, CSS, JavaScript)'}),
            'languages': forms.TextInput(attrs={'placeholder': 'Languages(separeted by , ex: English, French, Spanish)'}),
        }




# edit user info
class EditProfile(forms.ModelForm):
    username = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Username','autocomplete': 'off'}))
    email = forms.EmailField(max_length=100, required=False, widget=forms.EmailInput(attrs={'placeholder': 'Email','autocomplete': 'off'}))
    old_password = forms.CharField(
        max_length=100, 
        required=False, 
        label='Old Password(required if wanna change password)***',
        widget=forms.PasswordInput(attrs={'placeholder': 'Old Password**', 'autocomplete': 'off'})
    )
    new_password = forms.CharField(max_length=100, required=False, widget=forms.PasswordInput(attrs={'placeholder': 'New Password','autocomplete': 'off'}))
    class Meta:
        model = User
        fields = ['username','email','old_password','new_password','photo_profile','phone', 'address', 'city', 'country', 'Visibility']

    widgets = {
        'phone': forms.TextInput(attrs={'placeholder': 'Phone'}),
        'address': forms.TextInput(attrs={'placeholder': 'Address'}),
        'city': forms.TextInput(attrs={'placeholder': 'City'}),
        'country': forms.TextInput(attrs={'placeholder': 'Country'}),
        'photo_profile': forms.FileInput(attrs={'accept': 'image/*'}),
        }
    
#edit education
class EditEducation(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    class Meta:
        model = Cv
        fields = ['school', 'degree', 'start_dateE', 'end_dateE']
        widgets = {
            'school': forms.TextInput(attrs={'placeholder': 'School'}),
            'degree': forms.TextInput(attrs={'placeholder': 'Degree'}),
        }
#edit experience
class EditExperience(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

        
# edit cv 
class EditCV(forms.ModelForm):
    # if the cv is already exist show it avec le nom du fichier
    cv = forms.FileField(required=True, label='CV')
    class Meta:
        model = User
        fields = ['cv']

        widget = {
            'cv': forms.FileInput(attrs={'accept': '.pdf'}),
        }

##add experience
class ExperienceForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

#add education
class EducationForm(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={

Professional_Networking_Platform/PNP/templates/profilePage/education.html
{% load static %}
    <div class="plus-div " id="addEducation" data-id="2">
    <h2>Education</h2>
{% if isMe %}
    <i class="fa fa-plus plus-btn" data-id="2"></i>
{% endif %}
    </div>
    {% if cv.educations %}
    {% for education in cv.educations %} 
    <div class="profile-desc-row">
        <img src="{% static 'PNP/img/microsoft.png' %}">
        <div>
            <div class="plus-div " id="addEducation" data-id="2">
            <h3>{{education.school}}</h3>
            {% if isMe %}
            <i class="fa fa-trash deleteeduc plus-btn" data-id="{{education.id}}"></i>
            {% endif %}
            </div>
            <div class="plus-div " id="addEducation" data-id="{{education.id}}">
            <b>{{education.degree}}</b>
            {% if isMe %}
            <i class="fa fa-pencil editEduc plus-btn" data-id="{{education.id}}"></i>
            {% endif %}
            </div>
            <b>{{education.start_date}}-{{education.end_date}}</b>
            <hr>
        </div>
    </div>
    {% endfor %}
    {% else %}
        <div class="profile-desc-row">
            <div>
                <p>No education available</p>
            </div>
        </div> 
    {% endif %}

Professional_Networking_Platform/PNP/templates/profilePage/experience.html
{% load static %}
                <div class="plus-div" id="addExperience" data-id="1">
                <h2>Experience</h2>
{% if isMe %}
                <i class="fa fa-plus plus-btn" data-id="1"></i>
            {% endif %}
                </div>
{% if cv.experiences %}
                {% for experience in cv.experiences %}
                <div class="profile-desc-row">
                    <img src="{% static 'PNP/img/microsoft.png' %}">
                    <div>
                        <div class="plus-div" id="deleteExperi" data-id="{{experience.id}}">
                        <h3>{{experience.job_title}}</h3>
                        {% if isMe %}
                        <i class="fa fa-trash plus-btn deleteexp" data-id="{{experience.id}}"></i>
                        {% endif %}
                        </div>
                        <div class="plus-div " data-id="{{experience.id}}">
                        <b>{{experience.company}}</b>
                        {% if isMe %}
                        <i class="fa fa-pencil editExp plus-btn" data-id="{{experience.id}}"></i>
                        {% endif %}
                        </div>
                        <b>{{experience.start_date}}-{{experience.end_date}}</b>
                        <p>{{experience.description}}</p>
                        <hr>
                    </div>
                </div>
                {% endfor %}
            {% else %}
            <div class="profile-desc-row">
                <div>
                    <p>No experience available</p>
                </div>
            </div>
            {% endif %}

Professional_Networking_Platform/PNP/templates/profilePage/followBtn.html
{% load static %}

<style>
    .addFriend{
        cursor: pointer;
        display: inline-flex;
  align-items: center;
  background-color: #e4e6eb;
  padding: 6px 15px;
  border-radius: 4px;
  margin-right: 10px;
    }
    .addFriend img{
        width: 18px;
  margin-right: 5px;
    }
</style>
{% if requestsend %}

    <p style="background-color: #efefef;color:black" data-username="{{friend}}" class="primary-btn addFriend"><img src="{% static 'PNP/img/connect.png' %}" >waitting to be accepted</p>
{% else %}
    {% if isFriend %}
    
        <p style="background-color: #efefef;color:black" data-username="{{friend}}"  class="primary-btn addFriend"><img src="{% static 'PNP/img/connect.png' %}" >unfollow </p>
    {% else %}
        {% if is_private %}
            <p data-username="{{friend}}" class="primary-btn addFriend"><img src="{% static 'PNP/img/connect.png' %}" >send request</p>
        {% else %}
                <p data-username="{{friend}}" class="primary-btn addFriend"><img src="{% static 'PNP/img/connect.png' %}" >Connect</p>
        {% endif %}
    {% endif %}
{% endif %}

Professional_Networking_Platform/PNP/templates/profilePage/formProfile.html
{% load static %}
<style>
    #form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 95vh;
        margin: 0;
        background-color: #f8f9fa;
        font-family: Arial, sans-serif;
    }

    form {
        display: flex;
        flex-direction: column;
        width: 400px;
        gap: 20px;
        padding: 20px;
        background-color: white;
        box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
    }

    textarea {
        resize: none;
        width: 100%;
    }

    input, button, select, textarea {
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 5px;
        font-size: 16px;
        transition: all 0.3s ease;
        width: 100%;
    }

    input:focus, select:focus, textarea:focus {
        outline: none;
        border-color: #007bff;
        box-shadow: 0 0 5px #007bff;
    }

    button {
        background-color: #007bff;
        color: white;
        border: none;
    }

    button:hover {
        background-color: #0056b3;
    }
</style>
<form id="formProfile" style="overflow: scroll;max-height: 629px;" method="post" enctype="multipart/form-data" action="{% url 'PNP:formProfile' id auth_user.username %}">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    {{error}}
    <input type="reset" value="reset">
    <button type="submit" value="add">add</button>
</form>

Professional_Networking_Platform/PNP/templates/profilePage/formeduct.html
{% load static %}
<style>
    #form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 95vh;
        margin: 0;
        background-color: #f8f9fa;
        font-family: Arial, sans-serif;
    }

    form {
        display: flex;
        flex-direction: column;
        width: 400px;
        gap: 20px;
        padding: 20px;
        background-color: white;
        box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
    }

    textarea {
        resize: none;
        width: 100%;
    }

    input, button, select, textarea {
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 5px;
        font-size: 16px;
        transition: all 0.3s ease;
        width: 100%;
    }

    input:focus, select:focus, textarea:focus {
        outline: none;
        border-color: #007bff;
        box-shadow: 0 0 5px #007bff;
    }

    button {
        background-color: #007bff;
        color: white;
        border: none;
    }

    button:hover {
        background-color: #0056b3;
    }
</style>
<form  style="overflow: scroll;max-height: 629px;" method="post" enctype="multipart/form-data" action="{% url 'PNP:formEducation' id auth_user.username %}">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    {{error}}
    <input type="reset" value="reset">
    <button type="submit" value="add">add</button>
</form>

Professional_Networking_Platform/PNP/templates/profilePage/formexp.html
{% load static %}
<style>
    #form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 95vh;
        margin: 0;
        background-color: #f8f9fa;
        font-family: Arial, sans-serif;
    }

    form {
        display: flex;
        flex-direction: column;
        width: 400px;
        gap: 20px;
        padding: 20px;
        background-color: white;
        box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
    }

    textarea {
        resize: none;
        width: 100%;
    }

    input, button, select, textarea {
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 5px;
        font-size: 16px;
        transition: all 0.3s ease;
        width: 100%;
    }

    input:focus, select:focus, textarea:focus {
        outline: none;
        border-color: #007bff;
        box-shadow: 0 0 5px #007bff;
    }

    button {
        background-color: #007bff;
        color: white;
        border: none;
    }

    button:hover {
        background-color: #0056b3;
    }
</style>
<form id="formProfile" style="overflow: scroll;max-height: 629px;" method="post" enctype="multipart/form-data" action="{% url 'PNP:formExperience' id auth_user.username %}">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    {{error}}
    <input type="reset" value="reset">
    <button type="submit" value="add">add</button>
</form>

Professional_Networking_Platform/PNP/templates/profilePage/langs.html
{% load static %}
    <div class="plus-div" id="addlanguage" data-id="4">
    <h2>Languages</h2>
    {% if isMe %}
    <i class="fa fa-plus plus-btn" data-id="4"></i>
    {% endif %}
    </div>
    {% if cv.languages %}
    <div> {% for lang in cv.languages %}
        <div style="position:relative" class="lang-btn">{% if isMe %}<i style="position:absolute;transform: translate(50%,-100%);top: 0;right: 0;" class="fa fa-trash langdelete plus-btn" data-id="{{lang}}"></i>{% endif %}{{lang}}</div>{% if not forloop.last %} {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <p>No languages available</p>
{% endif %}

Professional_Networking_Platform/PNP/templates/profilePage/skills.html
{% load static %}
    <div class="plus-div" id="addSkills" data-id="3">
    <h2>Skills</h2>
    {% if isMe %}
    <i class="fa fa-plus plus-btn" data-id="3"></i>
    {% endif %}
    </div>
    {% if cv.skills %}
    <div> {% for skill in cv.skills %}
        
        <div style="position:relative" class="skill-btn">{% if isMe %}<i style="position:absolute;transform: translate(50%,-100%);top: 0;right: 0;" class="fa fa-trash skilldelete plus-btn" data-id="{{skill}}"></i>{% endif %}{{skill}}</div>{% if not forloop.last %} {% endif %}
        {% endfor %}
    </div>
    {% else %}
<p>No skills available</p>
{% endif %}