Professional_Networking_Platform/PNP/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import signUp,signUpEntre,signUp1,signUp2, firstPage,profile, messaging, metting, joinMetting, mettingPage, network, logincheck, like,classroom,get_comment,addFriend,signUpStud,search,formProfile,accept_request,reject_request, showCommentForm, addComment,create_cours,ouvrir_pdf, rejoindre_cours,get_posts,add_post,deletePost,ouvrir_pdf,delete_experience,delete_education,delete_skill,delete_language,formEducation,formExperience,roomCreateForm,searchRoom,rejoindre_cours, detail_cours,get_posts,add_post,deletePost,students_page,mes_cours,create_cours,getMessages,messageForm,travaux_et_devoir,creer_devoir,creer_documentation,quitterRoom,members,chat,searchPage,accueil,get_datapoints,update_course_view, delete_course_view,delete_documentation,delete_devoir


app_name = "PNP"

urlpatterns = [
    path("", firstPage , name='firstPage'),

    # registration
    path("", include("django.contrib.auth.urls")),
    path('signUp/', signUp1, name='signUp'),
    path('signUpEntre/', signUpEntre, name='signUpEntre'),
    path('signUpStud/', signUpStud, name='signUpStud'),
    path('signUp1/<int:choix>', signUp, name='signUp1'),
    path('signUp2/', signUp2, name='signUp2'),
    path('logincheck/', logincheck, name='logincheck'),

    # first page after login
    path('firstPage/', firstPage , name='firstPage'),

    # messaging page
    path('messaging/', messaging , name='messaging'),
    path('roomCreateForm/<int:type>/<int:id>/', roomCreateForm , name='roomCreateForm'),
    path('searchRoom/<str:roomname>/', searchRoom , name='searchRoom'),
    path('getMessages/<int:id>/', getMessages , name='getMessages'),
    path('messageForm/<int:id>/', messageForm , name='messageForm'),
    path('quitterRoom/<int:id>/', quitterRoom , name='quitterRoom'),
    path('members/<int:id>/', members , name='members'),
    
    # metting pages
    path('mettingPage/', mettingPage , name='mettingPage'), # metting choix page
    path('metting/', metting , name='metting'), # metting create page
    path('joinMetting/', joinMetting , name='joinMetting'), # metting join page

    # profile page
    path('profile/<str:username>/', profile , name='profile'),
    path('formProfile/<int:id>/<str:username>/', formProfile , name='formProfile'),
    path('delete_experience/<int:id>/<str:username>/', delete_experience , name='delete_experience'),
    path('delete_education/<int:id>/<str:username>/', delete_education , name='delete_education'),
    path('delete_skill/<str:id>/<str:username>/', delete_skill , name='delete_skill'),
    path('delete_language/<str:id>/<str:username>/', delete_language , name='delete_language'),
    path('formEducation/<int:id>/<str:username>/', formEducation , name='formEducation'),
    path('formExperience/<int:id>/<str:username>/', formExperience , name='formExperience'),
    path('chat/<str:username>/', chat , name='chat'),

    # clasroom page
    path('classroom/', classroom , name='classroom'),
    path('classroom/accueil/', accueil, name='accueil'),
     #createcourse
    path('classroom/create/', create_cours, name='create_cours'),
    path('ouvrir_pdf/', ouvrir_pdf, name='ouvrir_pdf'),
    
   
    
    
    # networking
    path('network/', network, name='network'),

    #friends
    path('addFriend/<str:friend>/', addFriend, name='addFriend'),
    path('accept_request/<str:username>', accept_request , name='accept_request'),
    path('reject_request/<str:username>', reject_request , name='reject_request'),

    #chart
    path('get_datapoints.json', get_datapoints, name='get_datapoints'),
    path('firstPage/get_datapoints.json', get_datapoints, name='get_datapoints'),
    
    #post
    path('posts/', get_posts , name='posts'),
    path('addPost/', add_post , name='addPost'),
    path('deletePost/<int:id>/', deletePost , name='deletePost'),
    path('like/<int:postid>/', like , name='like'),
    path('showCommentForm/<int:itemid>/<int:type>/', showCommentForm , name='showCommentForm'),
    path('comment/<int:itemid>/', get_comment , name='comment'),
    path('addComment/<int:itemid>/<int:type>/', addComment , name='addComment'),
    
    #pdf calendrier classroom
    #path('ouvrir-pdf/', ouvrir_pdf, name='ouvrir-pdf'),
    
    path('classroom/rejoindre_cours/', rejoindre_cours, name='rejoindre_cours'),  # Route pour rejoindre un cours
    path('classroom/detail_cours/<str:code>/', detail_cours, name='detail_cours'),
    path('classroom/detail_cours/<str:code>/students/', students_page, name='students_page'),

    path('mes_cours/', mes_cours, name='mes_cours'),

    path('classroom/detail_cours/<str:code>/travaux_et_devoir/', travaux_et_devoir, name='travaux_et_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/devoir/', creer_devoir, name='creer_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/documentation/', creer_documentation, name='creer_documentation'),
        
    path('classroom/detail_cours/<str:code>/update_course/', update_course_view, name='update_course'),
    path('classroom/detail_cours/<str:code_cours>/delete_course/', delete_course_view, name='delete_course'),
    
    path('classroom/detail_cours/<str:code>/delete_doc/<int:documentation_id>/', delete_documentation, name='delete_documentation'),
    path('classroom/detail_cours/<str:code_cours>/travaux_et_devoir/delete_devoir/<int:devoir_id>/', delete_devoir, name='delete_devoir'),
#search
    path('search/<str:username>/<int:type>/', search , name='search'),

    #search Page
    path('searchPage/', searchPage , name='searchPage'),
] + static(settings.STATIC_URL)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
print(settings.MEDIA_ROOT)

Professional_Networking_Platform/Professional_Networking_Platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PNP.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Professional_Networking_Platform/PNP/models/classe.py
from django.db import models
from .teacher import Teacher


#################
# Class model #
class Class(models.Model):
    class_id = models.AutoField(primary_key=True)
    class_name= models.CharField(max_length=100, default='')
    Degree = models.TextField(max_length=100, default='')
    
    #
   # teacher_id = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    #
    #
   # schedule_exams = models.TextField(default='[]')
    #
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.class_name

Professional_Networking_Platform/PNP/models/devoir.py
from django.db import models
from .Cours import Cours

class Devoir(models.Model):
    id = models.AutoField(primary_key=True)  # Ajout de l'identifiant unique
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE )
    titre = models.CharField(max_length=100)
    description = models.TextField()
    fichier_joint = models.FileField(upload_to='creer/devoir/', blank=True, null=True)
    date_limite = models.DateTimeField(blank=True)


    def __str__(self):
        return self.titre

    def get_devoirs_by_code(code_cours):
        return Devoir.objects.filter(cours__code=code_cours)
    
    def delete(self, *args, **kwargs):
        # Ajoutez ici la logique de suppression personnalisée si nécessaire
        super().delete(*args, **kwargs)

Professional_Networking_Platform/PNP/forms/forms.py
from django import forms

from ..models import User, Cv, Cours,Room,Devoir,Documentation
from django.contrib.auth.models import User as auth_user
from django.forms import SelectDateWidget


class MonthYearSelectWidget(SelectDateWidget):
    def __init__(self, *args, **kwargs):
        super(MonthYearSelectWidget, self).__init__(*args, **kwargs)
        self.format = '%Y-%m'  # Set the format to year-month

# signUp2
class SignUpForm(forms.ModelForm):
    introduction = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Introduction'}))
    class Meta:
        model = User
        fields = ['introduction','phone', 'address', 'city', 'country', 'cv', 'photo_profile', 'Visibility']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs['placeholder'] = 'Phone'
        self.fields['address'].widget.attrs['placeholder'] = 'Address'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        self.fields['country'].widget.attrs['placeholder'] = 'Country'


# signUp3
class CVForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company(optional)'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title(optional)'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School(optional)'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree(optional)'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description(optional)'}))
    class Meta:
        model = Cv
        fields = ['skills', 'languages','company', 'job_title', 'description' ,'start_date', 'end_date','school', 'degree', 'start_dateE', 'end_dateE']

        widgets = {
            'introduction': forms.TextInput(attrs={'placeholder': 'Introduction(optional)'}),
            'skills': forms.TextInput(attrs={'placeholder': 'Skills(separeted by , ex: HTML, CSS, JavaScript)'}),
            'languages': forms.TextInput(attrs={'placeholder': 'Languages(separeted by , ex: English, French, Spanish)'}),
        }




# edit user info
class EditProfile(forms.ModelForm):
    username = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Username','autocomplete': 'off'}))
    email = forms.EmailField(max_length=100, required=False, widget=forms.EmailInput(attrs={'placeholder': 'Email','autocomplete': 'off'}))
    old_password = forms.CharField(
        max_length=100, 
        required=False, 
        label='Old Password(required if wanna change password)***',
        widget=forms.PasswordInput(attrs={'placeholder': 'Old Password**', 'autocomplete': 'off'})
    )
    new_password = forms.CharField(max_length=100, required=False, widget=forms.PasswordInput(attrs={'placeholder': 'New Password','autocomplete': 'off'}))
    class Meta:
        model = User
        fields = ['username','email','old_password','new_password','photo_profile','phone', 'address', 'city', 'country', 'Visibility']

    widgets = {
        'phone': forms.TextInput(attrs={'placeholder': 'Phone'}),
        'address': forms.TextInput(attrs={'placeholder': 'Address'}),
        'city': forms.TextInput(attrs={'placeholder': 'City'}),
        'country': forms.TextInput(attrs={'placeholder': 'Country'}),
        'photo_profile': forms.FileInput(attrs={'accept': 'image/*'}),
        }
    
#edit education
class EditEducation(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    class Meta:
        model = Cv
        fields = ['school', 'degree', 'start_dateE', 'end_dateE']
        widgets = {
            'school': forms.TextInput(attrs={'placeholder': 'School'}),
            'degree': forms.TextInput(attrs={'placeholder': 'Degree'}),
        }
#edit experience
class EditExperience(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

        
# edit cv 
class EditCV(forms.ModelForm):
    # if the cv is already exist show it avec le nom du fichier
    cv = forms.FileField(required=True, label='CV')
    class Meta:
        model = User
        fields = ['cv']

        widget = {
            'cv': forms.FileInput(attrs={'accept': '.pdf'}),
        }

##add experience
class ExperienceForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

#add education
class EducationForm(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={

Professional_Networking_Platform/PNP/templates/messagePage/createMetting.html
    {% load static %}

<html>

<head>
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        #root {
            width: 100vw;
            height: 100vh;
        }
        .TYiiRFB3EhYJGVPE4k4q {
            display: none;
        }
        .VsTVUAD89KWleD0YRVsD{
            background-color: #00838D !important;
        }
        .overlay{
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 1;
      }
      .up{
        position: relative;
        z-index: 2;
      }
      .BYpXSnOHfrC2td4QRijO{
        background-image: url("{% static 'PNP/img/bgcs/backGround1.jpg'%}");
        background-size: cover;
      }
    </style>

    <title>Metting</title>
    <link rel="stylesheet" href="{% static 'PNP/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'PNP/css/choixMetting.css' %}">
</head>


<body>
    <div class="container">
            <a href="{% url 'PNP:mettingPage' %}" class="btn back" style="background-color: #00838D;margin: 10px"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>   Back</a>
    </div>

    <div id="root"></div>
</body>
<script src="https://unpkg.com/@zegocloud/zego-uikit-prebuilt/zego-uikit-prebuilt.js"></script>
<script>
window.onload = function () {
    //input value
    
    function getUrlParams(url) {
        let urlStr = url.split('?')[1];
        const urlSearchParams = new URLSearchParams(urlStr);
        const result = Object.fromEntries(urlSearchParams.entries());
        return result;
    }


        // Generate a Token by calling a method.
        // @param 1: appID
        // @param 2: serverSecret
        // @param 3: Room ID
        // @param 4: User ID
        // @param 5: Username
    const roomID = getUrlParams(window.location.href)
    ['roomID'] || (Math.floor(Math.random() * 10000) + "");
    const userID = Math.floor(Math.random() * 10000) + "";
    const userName = "{{username}}";
    const appID = 340922358;
    const serverSecret = "e31aee261ba139987a0c92ba2844267f";
    const kitToken = ZegoUIKitPrebuilt.generateKitTokenForTest(appID, serverSecret, roomID, userID, userName);

    
        const zp = ZegoUIKitPrebuilt.create(kitToken);
        zp.joinRoom({
            container: document.querySelector("#root"),
            sharedLinks: [{
                name: 'Room code',
                url: roomID,
            }],
            scenario: {
                mode: ZegoUIKitPrebuilt.VideoConference,
            },
                
           	turnOnMicrophoneWhenJoining: true,
           	turnOnCameraWhenJoining: true,
           	showMyCameraToggleButton: true,
           	showMyMicrophoneToggleButton: true,
           	showAudioVideoSettingsButton: true,
           	showScreenSharingButton: true,
           	showTextChat: true,
           	showUserList: true,
           	maxUsers: 60,
           	layout: "Auto",
           	showLayoutButton: false,
         
            });
            
}

</script>


</html>

Professional_Networking_Platform/PNP/templates/messagePage/joinMetting.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'PNP/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'PNP/css/choixMetting.css' %}">
    <style>
      .joinBtn{
        left: 50%;
        position: absolute;
        transform: translate(-50%);
        margin-top: 20px;
      }
      .overlay{
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        z-index: 1;
      }
      .up{
        position: relative;
        z-index: 2;
      }
      img{
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
    </style>
</head>
<body>
  <div class="overlay">
    <img src="{% static 'PNP/img/bgcs/backGround1.jpg'%}" ></img>
  </div>
  <div class="container up">
            {% if role == 1 %}
            <a href="{% url 'PNP:firstPage' %}" class="btn back " style="background-color: #00838D;margin: 10px"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            {% else %}
            <a href="{% url 'PNP:mettingPage' %}" class="btn back " style="background-color: #00838D;margin: 10px"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            {% endif %}
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>   Back</a>
    </div>
  <div class="d-flex align-items-center w-100 h-100 justify-content-center card">
    <div class="login up form card " style="background-color: #00838D;padding: 100px;border-radius:20px">
      <header class="h1">Join Room</header>
      <form action="{% url 'PNP:joinMetting' %}" method="POST">
        {% csrf_token %}
        <input class="form-control" style="margin-top:10px" type="text" placeholder="Enter room ID" name="roomID">
        <input type="submit" class="button btn joinBtn btn-primary" value="Join">
      </form>
    </div>
  </div>
</body>
</html>

Professional_Networking_Platform/PNP/templates/messagePage/members.html
{% load static %}

<ul>
            <li style="box-shadow: -1px 25px 37px -17px rgba(0,0,0,0.11);"  id="createRoom" data-type="3" data-id="{{room.room_ID}}">
                <a href="#"  id="createRoom" data-type="3"  data-id="{{room.room_ID}}">
                    <div class="contact"  id="createRoom" data-type="3"  data-id="{{room.room_ID}}">
                        <div data-type="3"  data-id="{{room.room_ID}}" class="message" style="text-align:center;position: relative;"  id="createRoom">+ add Members</div>
                    </div>
                </a>
            </li>
    {% for member in members %}
        <li style="display: flex;align-items: center;">
            {% if member.photo_profile %}
                <img style="
                border-radius: 50%;
                width: 40px;
                height: 40px;
                object-fit: cover;
                " src="{{ member.photo_profile.url }}" >
            {% else %}
                <img style="
                border-radius: 50%;
                width: 40px;
                height: 40px;
                object-fit: cover;
                " src="{% static 'PNP/media/avatar/default.jpg' %}" >
            {% endif %}
            <a style="margin-left:20px" href="{% url 'PNP:profile' member.user.username %}">
                {{ member.user.username }}
            </a>
        </li>
        
    {% endfor %}
</ul>

Professional_Networking_Platform/PNP/templates/messagePage/messagePage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Messaging</title>
    <link rel="stylesheet" href="{% static 'PNP/css/message.css' %}">
</head>
<body>
    <div class="chat" style="height: 92%;overflow: hidden;">
        {% include './message/sideBar/sideBar.html' %}
        {% include "./message/contentchat/content.html" %}

    </div>
    <script src="{% static 'PNP/js/messaging.js'%}"></script>
</body>
</html>
<script src="{% static 'PNP/js/msg.js' %}"></script>

{% endblock %}

Professional_Networking_Platform/PNP/templates/messagePage/mettingPage.html
{% load static %}

<head>
    <title>Metting</title>
    <link rel="stylesheet" href="{% static 'PNP/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'PNP/css/choixMetting.css' %}">
</head>
<div class="container w-100 h-100" style="overflow: hidden;">
            <a href="{% url 'PNP:firstPage' %}" class="btn back" style="background-color: #00838D;margin: 10px"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>   Home</a>
    <div class="d-flex align-items-center h-100 justify-content-around">
    <div class="card">
        <a class="card1" href="{% url 'PNP:metting' %}">
            <p>Create Metting</p>
            <p class="small">Start organizing your gatherings effortlessly with just one click!</p>
            <div class="go-corner" >
            <div class="go-arrow">
                →
            </div>
            </div>
        </a>
    </div>
    <div class="card">
        <a class="card1" href="{% url 'PNP:joinMetting' %}">
            <p>Join Metting</p>
            <p class="small">Easily connect to ongoing events with a single click.</p>
            <div class="go-corner" href="">
            <div class="go-arrow">
                →
            </div>
            </div>
        </a>
    </div>
    
    </div>
                
 </div>