Professional_Networking_Platform/PNP/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import signUp,signUpEntre,signUp1,signUp2, firstPage,profile, messaging, metting, joinMetting, mettingPage, network, logincheck, like,classroom,get_comment,addFriend,signUpStud,search,formProfile,accept_request,reject_request, showCommentForm, addComment,create_cours,ouvrir_pdf, rejoindre_cours,get_posts,add_post,deletePost,ouvrir_pdf,delete_experience,delete_education,delete_skill,delete_language,formEducation,formExperience,roomCreateForm,searchRoom,rejoindre_cours, detail_cours,get_posts,add_post,deletePost,students_page,mes_cours,create_cours,getMessages,messageForm,travaux_et_devoir,creer_devoir,creer_documentation,quitterRoom,members,chat,searchPage,accueil,get_datapoints,update_course_view, delete_course_view,delete_documentation,delete_devoir


app_name = "PNP"

urlpatterns = [
    path("", firstPage , name='firstPage'),

    # registration
    path("", include("django.contrib.auth.urls")),
    path('signUp/', signUp1, name='signUp'),
    path('signUpEntre/', signUpEntre, name='signUpEntre'),
    path('signUpStud/', signUpStud, name='signUpStud'),
    path('signUp1/<int:choix>', signUp, name='signUp1'),
    path('signUp2/', signUp2, name='signUp2'),
    path('logincheck/', logincheck, name='logincheck'),

    # first page after login
    path('firstPage/', firstPage , name='firstPage'),

    # messaging page
    path('messaging/', messaging , name='messaging'),
    path('roomCreateForm/<int:type>/<int:id>/', roomCreateForm , name='roomCreateForm'),
    path('searchRoom/<str:roomname>/', searchRoom , name='searchRoom'),
    path('getMessages/<int:id>/', getMessages , name='getMessages'),
    path('messageForm/<int:id>/', messageForm , name='messageForm'),
    path('quitterRoom/<int:id>/', quitterRoom , name='quitterRoom'),
    path('members/<int:id>/', members , name='members'),
    
    # metting pages
    path('mettingPage/', mettingPage , name='mettingPage'), # metting choix page
    path('metting/', metting , name='metting'), # metting create page
    path('joinMetting/', joinMetting , name='joinMetting'), # metting join page

    # profile page
    path('profile/<str:username>/', profile , name='profile'),
    path('formProfile/<int:id>/<str:username>/', formProfile , name='formProfile'),
    path('delete_experience/<int:id>/<str:username>/', delete_experience , name='delete_experience'),
    path('delete_education/<int:id>/<str:username>/', delete_education , name='delete_education'),
    path('delete_skill/<str:id>/<str:username>/', delete_skill , name='delete_skill'),
    path('delete_language/<str:id>/<str:username>/', delete_language , name='delete_language'),
    path('formEducation/<int:id>/<str:username>/', formEducation , name='formEducation'),
    path('formExperience/<int:id>/<str:username>/', formExperience , name='formExperience'),
    path('chat/<str:username>/', chat , name='chat'),

    # clasroom page
    path('classroom/', classroom , name='classroom'),
    path('classroom/accueil/', accueil, name='accueil'),
     #createcourse
    path('classroom/create/', create_cours, name='create_cours'),
    path('ouvrir_pdf/', ouvrir_pdf, name='ouvrir_pdf'),
    
   
    
    
    # networking
    path('network/', network, name='network'),

    #friends
    path('addFriend/<str:friend>/', addFriend, name='addFriend'),
    path('accept_request/<str:username>', accept_request , name='accept_request'),
    path('reject_request/<str:username>', reject_request , name='reject_request'),

    #chart
    path('get_datapoints.json', get_datapoints, name='get_datapoints'),
    path('firstPage/get_datapoints.json', get_datapoints, name='get_datapoints'),
    
    #post
    path('posts/', get_posts , name='posts'),
    path('addPost/', add_post , name='addPost'),
    path('deletePost/<int:id>/', deletePost , name='deletePost'),
    path('like/<int:postid>/', like , name='like'),
    path('showCommentForm/<int:itemid>/<int:type>/', showCommentForm , name='showCommentForm'),
    path('comment/<int:itemid>/', get_comment , name='comment'),
    path('addComment/<int:itemid>/<int:type>/', addComment , name='addComment'),
    
    #pdf calendrier classroom
    #path('ouvrir-pdf/', ouvrir_pdf, name='ouvrir-pdf'),
    
    path('classroom/rejoindre_cours/', rejoindre_cours, name='rejoindre_cours'),  # Route pour rejoindre un cours
    path('classroom/detail_cours/<str:code>/', detail_cours, name='detail_cours'),
    path('classroom/detail_cours/<str:code>/students/', students_page, name='students_page'),

    path('mes_cours/', mes_cours, name='mes_cours'),

    path('classroom/detail_cours/<str:code>/travaux_et_devoir/', travaux_et_devoir, name='travaux_et_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/devoir/', creer_devoir, name='creer_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/documentation/', creer_documentation, name='creer_documentation'),
        
    path('classroom/detail_cours/<str:code>/update_course/', update_course_view, name='update_course'),
    path('classroom/detail_cours/<str:code_cours>/delete_course/', delete_course_view, name='delete_course'),
    
    path('classroom/detail_cours/<str:code>/delete_doc/<int:documentation_id>/', delete_documentation, name='delete_documentation'),
    path('classroom/detail_cours/<str:code_cours>/travaux_et_devoir/delete_devoir/<int:devoir_id>/', delete_devoir, name='delete_devoir'),
#search
    path('search/<str:username>/<int:type>/', search , name='search'),

    #search Page
    path('searchPage/', searchPage , name='searchPage'),
] + static(settings.STATIC_URL)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
print(settings.MEDIA_ROOT)

Professional_Networking_Platform/Professional_Networking_Platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PNP.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Professional_Networking_Platform/PNP/models/classe.py
from django.db import models
from .teacher import Teacher


#################
# Class model #
class Class(models.Model):
    class_id = models.AutoField(primary_key=True)
    class_name= models.CharField(max_length=100, default='')
    Degree = models.TextField(max_length=100, default='')
    
    #
   # teacher_id = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    #
    #
   # schedule_exams = models.TextField(default='[]')
    #
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.class_name

Professional_Networking_Platform/PNP/models/devoir.py
from django.db import models
from .Cours import Cours

class Devoir(models.Model):
    id = models.AutoField(primary_key=True)  # Ajout de l'identifiant unique
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE )
    titre = models.CharField(max_length=100)
    description = models.TextField()
    fichier_joint = models.FileField(upload_to='creer/devoir/', blank=True, null=True)
    date_limite = models.DateTimeField(blank=True)


    def __str__(self):
        return self.titre

    def get_devoirs_by_code(code_cours):
        return Devoir.objects.filter(cours__code=code_cours)
    
    def delete(self, *args, **kwargs):
        # Ajoutez ici la logique de suppression personnalisée si nécessaire
        super().delete(*args, **kwargs)

Professional_Networking_Platform/PNP/forms/forms.py
from django import forms

from ..models import User, Cv, Cours,Room,Devoir,Documentation
from django.contrib.auth.models import User as auth_user
from django.forms import SelectDateWidget


class MonthYearSelectWidget(SelectDateWidget):
    def __init__(self, *args, **kwargs):
        super(MonthYearSelectWidget, self).__init__(*args, **kwargs)
        self.format = '%Y-%m'  # Set the format to year-month

# signUp2
class SignUpForm(forms.ModelForm):
    introduction = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Introduction'}))
    class Meta:
        model = User
        fields = ['introduction','phone', 'address', 'city', 'country', 'cv', 'photo_profile', 'Visibility']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs['placeholder'] = 'Phone'
        self.fields['address'].widget.attrs['placeholder'] = 'Address'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        self.fields['country'].widget.attrs['placeholder'] = 'Country'


# signUp3
class CVForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company(optional)'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title(optional)'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School(optional)'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree(optional)'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description(optional)'}))
    class Meta:
        model = Cv
        fields = ['skills', 'languages','company', 'job_title', 'description' ,'start_date', 'end_date','school', 'degree', 'start_dateE', 'end_dateE']

        widgets = {
            'introduction': forms.TextInput(attrs={'placeholder': 'Introduction(optional)'}),
            'skills': forms.TextInput(attrs={'placeholder': 'Skills(separeted by , ex: HTML, CSS, JavaScript)'}),
            'languages': forms.TextInput(attrs={'placeholder': 'Languages(separeted by , ex: English, French, Spanish)'}),
        }




# edit user info
class EditProfile(forms.ModelForm):
    username = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Username','autocomplete': 'off'}))
    email = forms.EmailField(max_length=100, required=False, widget=forms.EmailInput(attrs={'placeholder': 'Email','autocomplete': 'off'}))
    old_password = forms.CharField(
        max_length=100, 
        required=False, 
        label='Old Password(required if wanna change password)***',
        widget=forms.PasswordInput(attrs={'placeholder': 'Old Password**', 'autocomplete': 'off'})
    )
    new_password = forms.CharField(max_length=100, required=False, widget=forms.PasswordInput(attrs={'placeholder': 'New Password','autocomplete': 'off'}))
    class Meta:
        model = User
        fields = ['username','email','old_password','new_password','photo_profile','phone', 'address', 'city', 'country', 'Visibility']

    widgets = {
        'phone': forms.TextInput(attrs={'placeholder': 'Phone'}),
        'address': forms.TextInput(attrs={'placeholder': 'Address'}),
        'city': forms.TextInput(attrs={'placeholder': 'City'}),
        'country': forms.TextInput(attrs={'placeholder': 'Country'}),
        'photo_profile': forms.FileInput(attrs={'accept': 'image/*'}),
        }
    
#edit education
class EditEducation(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    class Meta:
        model = Cv
        fields = ['school', 'degree', 'start_dateE', 'end_dateE']
        widgets = {
            'school': forms.TextInput(attrs={'placeholder': 'School'}),
            'degree': forms.TextInput(attrs={'placeholder': 'Degree'}),
        }
#edit experience
class EditExperience(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

        
# edit cv 
class EditCV(forms.ModelForm):
    # if the cv is already exist show it avec le nom du fichier
    cv = forms.FileField(required=True, label='CV')
    class Meta:
        model = User
        fields = ['cv']

        widget = {
            'cv': forms.FileInput(attrs={'accept': '.pdf'}),
        }

##add experience
class ExperienceForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

#add education
class EducationForm(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={

Professional_Networking_Platform/PNP/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'PNP/css/firstPage.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    
</head>
<body>
    <nav class="navbar navnav" style="z-index: 2;">
        <div class="navbar-left">
            <a href="{% url 'PNP:firstPage' %}">
                <img src="{% static 'PNP/img/logo.svg' %}" class="logo">
            </a>
            
            {% comment %} <div class="search-box" style="position: relative;">
                <img src="./img/search.png' %}">
                <input id="search" type="text" placeholder="Search">
                
                <div style="overflow:scroll;max-height: 300px;height: 300px;position: absolute;top: 110%;background-color: #efefef;width: 100%;left: 0;border-radius: 5px 5px 10px 10px; display:none">
                
                </div>
            </div> {% endcomment %}
        </div>
        <div class="navbar-center">
        {% if auth_user.is_authenticated %}
            <ul>
                <li><a href="{% url 'PNP:firstPage' %}" class="{% if ishome %}active-link{% endif %}"><img src="{% static 'PNP/img/home.png' %}"><span>Home</span></a></li>
                <li><a href="{% url 'PNP:searchPage' %}" class="{% if isSearch %}active-link{% endif %}"><img style="width:20px;height:100%;opacity:0.6" src="{% static 'PNP/img/search1.svg' %}"><span>search</span></a></li>
                <li><a class="{% if isNetwork %}active-link{% endif %}" href="{% url 'PNP:network' %}"><img src="{% static 'PNP/img/network.png' %}"><span>My Network</span></a></li>
                <li><a class="{% if ismessaging %}active-link{% endif %}" href="{% url 'PNP:messaging' %}"><img src="{% static 'PNP/img/message.png' %}"><span>Messaging</span></a></li>
                <li><a class="{% if ismetting %}active-link{% endif %}" href="{% url 'PNP:mettingPage' %}"><img src="{% static 'PNP/img/notification.png' %}"><span>Metting</span></a></li>
                {% if role != 3 %}
                <li><a class="{% if isClassroom %}active-link{% endif %}" href="{% url 'PNP:classroom' %}"><img src="{% static 'PNP/img/jobs.png' %}"><span>classroom</span></a></li>
                {% endif %}
            </ul>
        {% else %}
        <h1>Guest Page</h1>
        {% endif %}
        </div>
        <div class="navbar-right">
        {% if auth_user.is_authenticated %}
            <div class="online">
                    {% if auth_user.user.photo_profile %}
                    <img style="object-fit: cover;height: 50px;width: 50px;" src="{{ auth_user.user.photo_profile.url }}" alt="" class="nav-profile-img" onclick="toggleMenu()">
                    {% else %}
                    <img src="{% static 'PNP/img/avatar/default.jpg' %}" alt="" class="nav-profile-img" onclick="toggleMenu()">
                    {% endif %}
            </div>
        {% else %}
            <a href="{% url 'PNP:login' %}" class="login">Login</a>
            <a href="{% url 'PNP:signUp' %}" class="register">Register</a>
        {% endif %}
        </div>
        <div class="profile-menu-wrap" id="profileMenu">
            <div class="profile-menu">
            {% if auth_user.is_authenticated%}
                <div class="user-info">
                    {% if auth_user.user.photo_profile %}
                    <img style="object-fit: cover;height: 100px;width: 95px;" src="{{ auth_user.user.photo_profile.url }}" alt="">
                    {% else %}
                    <img src="{% static 'PNP/img/avatar/default.jpg' %}" alt="">
                    {% endif %}
                    <div>
                        <h3>{{auth_user.username}}</h3>
                        
                    </div>
                </div>
            
                <hr>
                <a href="{% url 'PNP:profile' auth_user.username %}" class="profile-menu-link">
                    <img src="{% static 'PNP/img/display.png' %}">
                    <p>See Your Profile</p>
                    <span>></span>
                </a>
                {% comment %} <a href="" class="profile-menu-link">
                    <img src="{% static 'PNP/img/feedback.png' %}">
                    <p>My Requests</p>
                    <span>></span>
                </a> {% endcomment %}
                <form class="profile-menu-link" style="display: flex;align-items: center;justify-content: space-between;"  action="{% url 'PNP:logout' %}" method="post" >
                 {% csrf_token %}
                    <img style="width: 35px;" src="{% static 'PNP/img/logout.png' %}">
                <button type="submit"  class="profile-menu-link" style="padding: 5px;border-radius: 10px;border:none">Logout</button>
                </form>


            {% endif %}
            </div>
        </div>
    </nav>
    {% block content %}
    
    {% endblock content %}
    
    <script src="{% static 'PNP/js/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'PNP/js/firstPage.js' %}"></script>
    <script>
    var search = document.getElementById('search');
    var searchBox = document.querySelector('.search-box div');

    search.addEventListener('keyup',()=>{
            searchBox.style.display = 'block';
        searchBox.innerHTML = '';
        $.ajax({
        url: '/search/' + search.value + '/'+0+'/',
        type: 'GET',
        success: function (response) {
            searchBox.innerHTML = response;
        }
    });
    })

    function fetchProfiles(){
        fetch('/fetchFriends')
        .then(res=>res.json())
        .then(data=>{
            console.log(data);
        })
    }
    </script>
</body>
</html>