Professional_Networking_Platform/PNP/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import signUp,signUpEntre,signUp1,signUp2, firstPage,profile, messaging, metting, joinMetting, mettingPage, network, logincheck, like,classroom,get_comment,addFriend,signUpStud,search,formProfile,accept_request,reject_request, showCommentForm, addComment,create_cours,ouvrir_pdf, rejoindre_cours,get_posts,add_post,deletePost,ouvrir_pdf,delete_experience,delete_education,delete_skill,delete_language,formEducation,formExperience,roomCreateForm,searchRoom,rejoindre_cours, detail_cours,get_posts,add_post,deletePost,students_page,mes_cours,create_cours,getMessages,messageForm,travaux_et_devoir,creer_devoir,creer_documentation,quitterRoom,members,chat,searchPage,accueil,get_datapoints,update_course_view, delete_course_view,delete_documentation,delete_devoir


app_name = "PNP"

urlpatterns = [
    path("", firstPage , name='firstPage'),

    # registration
    path("", include("django.contrib.auth.urls")),
    path('signUp/', signUp1, name='signUp'),
    path('signUpEntre/', signUpEntre, name='signUpEntre'),
    path('signUpStud/', signUpStud, name='signUpStud'),
    path('signUp1/<int:choix>', signUp, name='signUp1'),
    path('signUp2/', signUp2, name='signUp2'),
    path('logincheck/', logincheck, name='logincheck'),

    # first page after login
    path('firstPage/', firstPage , name='firstPage'),

    # messaging page
    path('messaging/', messaging , name='messaging'),
    path('roomCreateForm/<int:type>/<int:id>/', roomCreateForm , name='roomCreateForm'),
    path('searchRoom/<str:roomname>/', searchRoom , name='searchRoom'),
    path('getMessages/<int:id>/', getMessages , name='getMessages'),
    path('messageForm/<int:id>/', messageForm , name='messageForm'),
    path('quitterRoom/<int:id>/', quitterRoom , name='quitterRoom'),
    path('members/<int:id>/', members , name='members'),
    
    # metting pages
    path('mettingPage/', mettingPage , name='mettingPage'), # metting choix page
    path('metting/', metting , name='metting'), # metting create page
    path('joinMetting/', joinMetting , name='joinMetting'), # metting join page

    # profile page
    path('profile/<str:username>/', profile , name='profile'),
    path('formProfile/<int:id>/<str:username>/', formProfile , name='formProfile'),
    path('delete_experience/<int:id>/<str:username>/', delete_experience , name='delete_experience'),
    path('delete_education/<int:id>/<str:username>/', delete_education , name='delete_education'),
    path('delete_skill/<str:id>/<str:username>/', delete_skill , name='delete_skill'),
    path('delete_language/<str:id>/<str:username>/', delete_language , name='delete_language'),
    path('formEducation/<int:id>/<str:username>/', formEducation , name='formEducation'),
    path('formExperience/<int:id>/<str:username>/', formExperience , name='formExperience'),
    path('chat/<str:username>/', chat , name='chat'),

    # clasroom page
    path('classroom/', classroom , name='classroom'),
    path('classroom/accueil/', accueil, name='accueil'),
     #createcourse
    path('classroom/create/', create_cours, name='create_cours'),
    path('ouvrir_pdf/', ouvrir_pdf, name='ouvrir_pdf'),
    
   
    
    
    # networking
    path('network/', network, name='network'),

    #friends
    path('addFriend/<str:friend>/', addFriend, name='addFriend'),
    path('accept_request/<str:username>', accept_request , name='accept_request'),
    path('reject_request/<str:username>', reject_request , name='reject_request'),

    #chart
    path('get_datapoints.json', get_datapoints, name='get_datapoints'),
    path('firstPage/get_datapoints.json', get_datapoints, name='get_datapoints'),
    
    #post
    path('posts/', get_posts , name='posts'),
    path('addPost/', add_post , name='addPost'),
    path('deletePost/<int:id>/', deletePost , name='deletePost'),
    path('like/<int:postid>/', like , name='like'),
    path('showCommentForm/<int:itemid>/<int:type>/', showCommentForm , name='showCommentForm'),
    path('comment/<int:itemid>/', get_comment , name='comment'),
    path('addComment/<int:itemid>/<int:type>/', addComment , name='addComment'),
    
    #pdf calendrier classroom
    #path('ouvrir-pdf/', ouvrir_pdf, name='ouvrir-pdf'),
    
    path('classroom/rejoindre_cours/', rejoindre_cours, name='rejoindre_cours'),  # Route pour rejoindre un cours
    path('classroom/detail_cours/<str:code>/', detail_cours, name='detail_cours'),
    path('classroom/detail_cours/<str:code>/students/', students_page, name='students_page'),

    path('mes_cours/', mes_cours, name='mes_cours'),

    path('classroom/detail_cours/<str:code>/travaux_et_devoir/', travaux_et_devoir, name='travaux_et_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/devoir/', creer_devoir, name='creer_devoir'),
    path('classroom/detail_cours/<str:code>/travaux_et_devoir/creer/documentation/', creer_documentation, name='creer_documentation'),
        
    path('classroom/detail_cours/<str:code>/update_course/', update_course_view, name='update_course'),
    path('classroom/detail_cours/<str:code_cours>/delete_course/', delete_course_view, name='delete_course'),
    
    path('classroom/detail_cours/<str:code>/delete_doc/<int:documentation_id>/', delete_documentation, name='delete_documentation'),
    path('classroom/detail_cours/<str:code_cours>/travaux_et_devoir/delete_devoir/<int:devoir_id>/', delete_devoir, name='delete_devoir'),
#search
    path('search/<str:username>/<int:type>/', search , name='search'),

    #search Page
    path('searchPage/', searchPage , name='searchPage'),
] + static(settings.STATIC_URL)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
print(settings.MEDIA_ROOT)

Professional_Networking_Platform/Professional_Networking_Platform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PNP.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Professional_Networking_Platform/PNP/models/classe.py
from django.db import models
from .teacher import Teacher


#################
# Class model #
class Class(models.Model):
    class_id = models.AutoField(primary_key=True)
    class_name= models.CharField(max_length=100, default='')
    Degree = models.TextField(max_length=100, default='')
    
    #
   # teacher_id = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    #
    #
   # schedule_exams = models.TextField(default='[]')
    #
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.class_name

Professional_Networking_Platform/PNP/models/devoir.py
from django.db import models
from .Cours import Cours

class Devoir(models.Model):
    id = models.AutoField(primary_key=True)  # Ajout de l'identifiant unique
    cours = models.ForeignKey(Cours, on_delete=models.CASCADE )
    titre = models.CharField(max_length=100)
    description = models.TextField()
    fichier_joint = models.FileField(upload_to='creer/devoir/', blank=True, null=True)
    date_limite = models.DateTimeField(blank=True)


    def __str__(self):
        return self.titre

    def get_devoirs_by_code(code_cours):
        return Devoir.objects.filter(cours__code=code_cours)
    
    def delete(self, *args, **kwargs):
        # Ajoutez ici la logique de suppression personnalisée si nécessaire
        super().delete(*args, **kwargs)

Professional_Networking_Platform/PNP/forms/forms.py
from django import forms

from ..models import User, Cv, Cours,Room,Devoir,Documentation
from django.contrib.auth.models import User as auth_user
from django.forms import SelectDateWidget


class MonthYearSelectWidget(SelectDateWidget):
    def __init__(self, *args, **kwargs):
        super(MonthYearSelectWidget, self).__init__(*args, **kwargs)
        self.format = '%Y-%m'  # Set the format to year-month

# signUp2
class SignUpForm(forms.ModelForm):
    introduction = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Introduction'}))
    class Meta:
        model = User
        fields = ['introduction','phone', 'address', 'city', 'country', 'cv', 'photo_profile', 'Visibility']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs['placeholder'] = 'Phone'
        self.fields['address'].widget.attrs['placeholder'] = 'Address'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        self.fields['country'].widget.attrs['placeholder'] = 'Country'


# signUp3
class CVForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company(optional)'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title(optional)'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School(optional)'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree(optional)'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description(optional)'}))
    class Meta:
        model = Cv
        fields = ['skills', 'languages','company', 'job_title', 'description' ,'start_date', 'end_date','school', 'degree', 'start_dateE', 'end_dateE']

        widgets = {
            'introduction': forms.TextInput(attrs={'placeholder': 'Introduction(optional)'}),
            'skills': forms.TextInput(attrs={'placeholder': 'Skills(separeted by , ex: HTML, CSS, JavaScript)'}),
            'languages': forms.TextInput(attrs={'placeholder': 'Languages(separeted by , ex: English, French, Spanish)'}),
        }




# edit user info
class EditProfile(forms.ModelForm):
    username = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Username','autocomplete': 'off'}))
    email = forms.EmailField(max_length=100, required=False, widget=forms.EmailInput(attrs={'placeholder': 'Email','autocomplete': 'off'}))
    old_password = forms.CharField(
        max_length=100, 
        required=False, 
        label='Old Password(required if wanna change password)***',
        widget=forms.PasswordInput(attrs={'placeholder': 'Old Password**', 'autocomplete': 'off'})
    )
    new_password = forms.CharField(max_length=100, required=False, widget=forms.PasswordInput(attrs={'placeholder': 'New Password','autocomplete': 'off'}))
    class Meta:
        model = User
        fields = ['username','email','old_password','new_password','photo_profile','phone', 'address', 'city', 'country', 'Visibility']

    widgets = {
        'phone': forms.TextInput(attrs={'placeholder': 'Phone'}),
        'address': forms.TextInput(attrs={'placeholder': 'Address'}),
        'city': forms.TextInput(attrs={'placeholder': 'City'}),
        'country': forms.TextInput(attrs={'placeholder': 'Country'}),
        'photo_profile': forms.FileInput(attrs={'accept': 'image/*'}),
        }
    
#edit education
class EditEducation(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),

    )
    class Meta:
        model = Cv
        fields = ['school', 'degree', 'start_dateE', 'end_dateE']
        widgets = {
            'school': forms.TextInput(attrs={'placeholder': 'School'}),
            'degree': forms.TextInput(attrs={'placeholder': 'Degree'}),
        }
#edit experience
class EditExperience(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

        
# edit cv 
class EditCV(forms.ModelForm):
    # if the cv is already exist show it avec le nom du fichier
    cv = forms.FileField(required=True, label='CV')
    class Meta:
        model = User
        fields = ['cv']

        widget = {
            'cv': forms.FileInput(attrs={'accept': '.pdf'}),
        }

##add experience
class ExperienceForm(forms.ModelForm):
    company = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    job_title = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'job_title'}))
    start_date = forms.CharField(required=False,max_length=100,
        widget=MonthYearSelectWidget(
            years=range(1980, 2025),
            empty_label=("Choose Year", "Choose Month", "Jour"),
        ),
    )
    end_date = forms.CharField(required=False,max_length=100,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        
    )
    description = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Experience description'}))
    class Meta:
        model = Cv
        fields = ['company', 'job_title', 'start_date', 'end_date', 'description']

#add education
class EducationForm(forms.ModelForm):
    school = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'School'}))
    degree = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Degree'}))
    start_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={
            1: 'Janvier', 2: 'Février', 3: 'Mars', 4: 'Avril',
            5: 'Mai', 6: 'Juin', 7: 'Juillet', 8: 'Août',
            9: 'Septembre', 10: 'Octobre', 11: 'Novembre', 12: 'Décembre'
        }, empty_label=("Choisir l'année", "Choisir le mois", "Jour")),
        )
    end_dateE = forms.CharField(required=False,
        widget=forms.SelectDateWidget(years=range(1980, 2025), months={

Professional_Networking_Platform/PNP/templates/firstPage/addComment.html
    <div class="fotter-comment" style="flex-direction: column;width:100%;left: 0;">

{% if is_reply and comment %}
    <div id="ReplyContainer" style="width:100%">
	<div class="new_comment" >

			<!-- build comment -->
		 	<ul class="user_comment">

		 		<!-- current #{user} avatar -->
			 	<div class="user_avatar">
				{% if comment.user_id.photo_profile %}
                    <img style="width: 40px; height: 40px;object-fit: cover;"  src="{{comment.user_id.photo_profile.url}}">
				{% else %}
				<img src="/media/avatar/default.jpg">
				{% endif %}
			 		
			 	</div><!-- the comment body --><div class="comment_body" style="min-height: 0">
                <div class="replied_to"><p><a href="{% url 'PNP:profile' comment.user_id.user.username %}"><span class="user">{{comment.user_id.user.username}}:</span></a>{{comment.comment}}</p></div>
					</div>
			 	</div>

            </ul>
            <div onclick="removeReply()" style="position: absolute; top: 0; right: 20px; cursor: pointer;">x</div>
        </div>
    

{% endif %}
<div style="display:flex;justify-content: space-between;align-items: center;width:100%;left: 0;">
        {% comment %} <form style="width:100%" method="post" action="{% url 'PNP:addComment' itemId type %}"> {% endcomment %}
            {% comment %} {% csrf_token %} {% endcomment %}
                <div class="user_avatar" style="">
                    {% if user.user.photo_profile %}
                    <img style="object-fit: cover;height: 50px;width: 50px;"
                        src="{{user.user.photo_profile.url}}">
                    {% else %}
                    <img src="/media/avatar/default.jpg">
                    {% endif %}
                </div>
		 		<input name="commentContent" id="commentContent" type="text" class="commentFilied" placeholder="Write a comment" style="width: 63%;" required>
                <button class="btn" onclick="addComment({{itemId}},{{type}},{{postId}})" type="submit">Comment</button>
                
		 	</div>
        {% comment %} </form> {% endcomment %}
        
    </div>
    </div>
    

Professional_Networking_Platform/PNP/templates/firstPage/comments.html
	{% load static %}
	<link rel="stylesheet" href="{% static 'PNP/css/comment.css' %}">
    <link rel="stylesheet" href="{% static 'PNP/css/comment2.css' %}">
    <div class="overlay" onclick="closeComment()" id="overlay"></div>
    <div id="commentSection" style="right: -600px;">
        <div class="comment_block" style="height: 91%;">

		
    <div id="comments">
	<div id="headercomment"></div>
	{% if auth_user.is_authenticated%}
	<div id="footercomment"></div>
	
	{% endif %}
	</div>
	</div>
	</div>


    <script src="{% static 'PNP/js/comment.js' %}"></script>

    <script src="{% static 'PNP/js/jquery-3.7.1.min.js' %}"></script>

Professional_Networking_Platform/PNP/templates/firstPage/commentsFrom.html
	
	<div class="new_comment">

			<!-- build comment -->
			{% for comment in comments %}
		 	<ul class="user_comment" style="margin-bottom: 30px;margin-top: 20px;">

		 		<!-- current #{user} avatar -->
			 	<div class="user_avatar">
				{% if comment.user_id.photo_profile %}
                    <img style="width: 40px; height: 40px;object-fit: cover;"  src="{{comment.user_id.photo_profile.url}}">
				{% else %}
				<img src="/media/avatar/default.jpg">
				{% endif %}
			 		
			 	</div><!-- the comment body --><div class="comment_body">
			 		<p>{{comment.comment}}</p>
			 	</div>

			 	<!-- comments toolbar -->
			 	<div class="comment_toolbar">

			 		<!-- inc. date and time -->
			 		<div class="comment_details">
			 			<ul>
			 				<li><i class="fa fa-clock-o"></i> {{comment.created_at|date:"H:i"}}</li>
							<li><i class="fa fa-calendar"></i> {{comment.created_at|date:"d/m/y"}}</li>
			 				<li><i class="fa fa-pencil"></i><a href="{% url 'PNP:profile' comment.user_id.user.username %}"> <span class="user">{{comment.user_id.user.username}}</span></a></li>
			 			</ul>
			 		</div><!-- inc. share/reply and love --><div class="comment_tools">
			 			<ul>
			 				<li><i class="fa fa-reply" onclick="fetchFormComment({{comment.id}},2)"> {{comment.number_of_replies}}</i></li>
			 				<li ><i class="fa fa-heart love"><span class="love_amt"> {{comment.number_of_likes}}</span></i></li>
			 			</ul>
			 		</div>

			 	</div>

			 	<!-- start user replies -->
				<div>
				{% for reply in comment.replies.all %}
				<li>
					<!-- current #{user} avatar -->
					<div class="user_avatar">
						{% if reply.user_id.photo_profile %}
                    		<img style="width: 40px; height: 40px;object-fit: cover;" src="{{reply.user_id.photo_profile.url}}">
						{% else %}
							<img src="/media/avatar/default.jpg">
						{% endif %}
					</div><!-- the comment body --><div class="comment_body">
						<p><div class="replied_to"><p><a href="{% url 'PNP:profile' reply.user_id.user.username %}"><span class="user">{{reply.user_id.user.username}}:</span></a>{{comment.comment}}</p></div>{{reply.comment}}</p>
					</div>

					<!-- comments toolbar -->
					<div class="comment_toolbar">

						<!-- inc. date and time -->
						<div class="comment_details">
							<ul>
								<li><i class="fa fa-clock-o"></i> {{reply.created_at|date:"H:i"}}</li>
								<li><i class="fa fa-calendar"></i> {{reply.created_at|date:"d/m/y"}}</li>
								<li><i class="fa fa-pencil"></i> <span class="user"><a href="{% url 'PNP:profile' reply.user_id.user.username %}"> <span class="user">{{reply.user_id.user.username}}</span></a></span></li>
							</ul>
						</div><!-- inc. share/reply and love --><div class="comment_tools">
							<ul>
								<li><i class="fa fa-reply" onclick="fetchFormComment({{reply.id}},2)"></i> {{reply.number_of_replies}}</li>
								<li><i class="fa fa-heart love"><span class="love_amt"> {{reply.number_of_likes}}</span></i></li>
							</ul>
						</div>
						{% for reply2 in reply.replies.all %}
				<li>
					<!-- current #{user} avatar -->
					<div class="user_avatar">
						{% if reply2.user_id.photo_profile %}
                    		<img style="width: 40px; height: 40px;object-fit: cover;" src="{{reply2.user_id.photo_profile.url}}">
						{% else %}
							<img src="/media/avatar/default.jpg">
						{% endif %}
					</div><!-- the comment body --><div class="comment_body">
						<p><div class="replied_to"><p><a href="{% url 'PNP:profile' reply2.user_id.user.username %}"><span class="user">{{reply2.user_id.user.username}}:</span></a>{{reply.comment}}</p></div>{{reply2.comment}}</p>
					</div>

					<!-- comments toolbar -->
					<div class="comment_toolbar">

						<!-- inc. date and time -->
						<div class="comment_details">
							<ul>
								<li><i class="fa fa-clock-o"></i> {{reply2.created_at|date:"H:i"}}</li>
								<li><i class="fa fa-calendar"></i> {{reply2.created_at|date:"d/m/y"}}</li>
								<li><i class="fa fa-pencil"></i> <span class="user"><a href="{% url 'PNP:profile' reply2.user_id.user.username %}"> <span class="user">{{reply2.user_id.user.username}}</span></a></span></li>
							</ul>
						

					</div>


				</li>
				{% endfor %}
					</div>


				</li>
				{% endfor %}
		 	</ul>
			<hr style="height:1px;border-width:0;color:#333;background-color:#333;width:50%;margin-left:auto;margin-right:auto;opacity:0.3">
			{% endfor %}

		 </div>

Professional_Networking_Platform/PNP/templates/firstPage/search.html
<style>
    .user-list {
        font-family: Arial, sans-serif;
        padding: 0;
        margin: 0;
    }
    .user-list li {
        list-style-type: none;
        background-color: #f0f0f0;
        border: 1px solid #ccc;
        margin-bottom: 10px;
        padding: 10px;
        transition: background-color 0.3s ease;
    }
    .user-list li:hover {
        background-color: #e0e0e0;
    }
    .user-list a {
        text-decoration: none;
        color: #333;
    }
    .no-users {
        font-family: Arial, sans-serif;
        color: #999;
    }
    .filter-buttons {
        margin-bottom: 10px;
    }
    .filter-buttons button {
        background-color: #00838D; /* Green */
        border: none;
        color: white;
        padding: 10px 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin-right: 2px;
        cursor: pointer;
    }
    .filter-buttons button:hover {
        background-color: #017078;
    }
</style>



{% if users %}
    <ul class="user-list">
        {% for user in users %}
            <li>
                <a href="{% url 'PNP:profile' user.user.username %}">
                    {{ user.user.username }}
                    {% if user.role == 3 %} 
                    · {{user.introduction}} Company
                    {% endif %}
                    {% if user.role == 1 %} · Student {% endif %}
                    {% if user.role == 2 %} · Teacher {% endif %}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p class="no-users">No users found</p>
{% endif %}